/*
DEV - MICHELE SOUZA
*/

CREATE DATABASE ANTILA 
GO

IF NOT EXISTS(SELECT * FROM SYS.TABLES WHERE NAME = 'PRODUTO')
BEGIN
	CREATE TABLE PRODUTO
	(
		 COD_PRODUTO CHAR(4) PRIMARY KEY NOT NULL
		,DES_PRODUTO VARCHAR(30)
		,STA_STATUS CHAR(1) NOT NULL DEFAULT('A') CHECK(STA_STATUS IN ('A', 'I'))
	)
	/*
	STATUS DO REGISTRO 
	(A) ATIVO
	(I) INATIVO
	*/
END
GO


IF NOT EXISTS(SELECT * FROM SYS.TABLES WHERE NAME = 'PRODUTO_COSIF')
BEGIN
	CREATE TABLE PRODUTO_COSIF
	(
		 COD_PRODUTO CHAR(4) FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO
		,COD_COSIF CHAR(11) PRIMARY KEY NOT NULL
		,COD_CLASSIFICACAO CHAR(6)
		,STA_STATUS CHAR(1) NOT NULL DEFAULT('A') CHECK(STA_STATUS IN ('A', 'I'))
	)

	/*
	STATUS DO REGISTRO 
	(A) ATIVO
	(I) INATIVO
	*/

END
GO

IF NOT EXISTS(SELECT * FROM SYS.TABLES WHERE NAME = 'MOVIMENTO_MANUAL')
BEGIN
	CREATE TABLE MOVIMENTO_MANUAL
	(
			 DAT_MES INT NOT NULL
			,DAT_ANO INT NOT NULL
			,NUM_LANCAMENTO INT NOT NULL PRIMARY KEY IDENTITY(1,1) 
			,COD_PRODUTO CHAR(4) NOT NULL 
			,COD_COSIF CHAR(11) FOREIGN KEY (COD_COSIF) REFERENCES PRODUTO_COSIF
			,VAL_VALOR DECIMAL(18,2) DEFAULT(0) NOT NULL
			,DES_MOVIMENTO VARCHAR(50) NOT NULL
			,DAT_MOVIMENTO DATETIME NOT NULL DEFAULT(CONVERT(datetime, SYSDATETIMEOFFSET() AT TIME ZONE 'E. South America Standard Time')) 
			,COD_USUARIO VARCHAR(15) NOT NULL 
		)

END
GO

IF EXISTS (select * from sys.procedures where name = 'USP_MOVIMENTO_MANUAIS_GET')
BEGIN
	DROP PROC USP_MOVIMENTO_MANUAIS_GET
END
GO

CREATE PROC USP_MOVIMENTO_MANUAIS_GET
( 
	  @STA_STATUS CHAR = NULL
) 
AS 
BEGIN 
	SELECT 
		 M.DAT_MES,
		 M.DAT_ANO,
		 M.COD_PRODUTO,
		 M.NUM_LANCAMENTO,
	     M.DES_MOVIMENTO,
		 M.COD_COSIF,
		 M.VAL_VALOR,
		 P.DES_PRODUTO,
		 P.STA_STATUS
	 FROM 
		MOVIMENTO_MANUAL AS M
		JOIN 
		PRODUTO P 
		ON 
		M.COD_PRODUTO = P.COD_PRODUTO
 	 WHERE 
		P.STA_STATUS = COALESCE(@STA_STATUS, P.STA_STATUS)

		ORDER BY 
		 M.DAT_MES,
		 M.DAT_ANO,
		 M.NUM_LANCAMENTO 
END 
GO


IF EXISTS (select * from sys.procedures where name = 'USP_PRODUTO_COSIF_GET')
BEGIN
	DROP PROC USP_PRODUTO_COSIF_GET
END
GO

CREATE PROC USP_PRODUTO_COSIF_GET
( 
	  @STA_STATUS CHAR = NULL,
	  @Cod_Produto CHAR = NULL
) 
AS 
BEGIN 
	SELECT 
		 C.COD_COSIF,
		 C.COD_CLASSIFICACAO,
		 P.DES_PRODUTO,
		 P.STA_STATUS,
		 P.Cod_Produto
	 FROM 
		PRODUTO_COSIF AS C
		JOIN 
		PRODUTO P 
		ON 
		C.COD_PRODUTO = P.COD_PRODUTO
 	 WHERE 
		P.STA_STATUS = COALESCE(@STA_STATUS, P.STA_STATUS)
		and 
		P.COD_PRODUTO = COALESCE(@COD_PRODUTO, P.COD_PRODUTO)
		
END 
GO

IF EXISTS (select * from sys.procedures where name = 'USP_MOVIMENTO_MANUAL_SET')
BEGIN
	DROP PROC USP_MOVIMENTO_MANUAL_SET
END
GO
  
CREATE PROC USP_MOVIMENTO_MANUAL_SET  
(   
   @DAT_MES INT = NULL,  
   @DAT_ANO INT = NULL,  
   @COD_PRODUTO CHAR = NULL,  
   @COD_COSIF CHAR = NULL,  
   @VAL_VALOR DECIMAL = NULL,  
   @DES_MOVIMENTO VARCHAR(50) = NULL,  
   @COD_USUARIO VARCHAR(15) = NULL,  
   @NUM_LANCAMENTO INT = NULL  
  
)   
AS   
BEGIN   
 IF @NUM_LANCAMENTO IS NULL  
 BEGIN    
  INSERT INTO MOVIMENTO_MANUAL  
  (  
    DAT_MES  
   ,DAT_ANO  
   ,COD_PRODUTO  
   ,COD_COSIF  
   ,VAL_VALOR  
   ,DES_MOVIMENTO  
   ,COD_USUARIO  
  
  
  )SELECT  
    @DAT_MES  
   ,@DAT_ANO  
   ,@COD_PRODUTO  
   ,@COD_COSIF  
   ,@VAL_VALOR  
   ,@DES_MOVIMENTO  
   ,@COD_USUARIO  
  SET @NUM_LANCAMENTO = @@IDENTITY  
 END  
 ELSE  
 BEGIN  
  UPDATE MOVIMENTO_MANUAL SET  
    @DAT_MES = @DAT_MES  
   ,@DAT_ANO = @DAT_ANO  
   ,@COD_PRODUTO = @COD_PRODUTO  
   ,@DES_MOVIMENTO = @DES_MOVIMENTO  
  WHERE  
   NUM_LANCAMENTO = @NUM_LANCAMENTO  
 END  
 SELECT @NUM_LANCAMENTO  
END   
GO


insert into PRODUTO VALUES('1' , 'PRODUTO TESTE', 'CLAS01','A')
insert into PRODUTO VALUES('1' , 'PRODUTO TESTE 2', 'CLAS01','A')
insert into PRODUTO_COSIF VALUES('1' , '1', 'CLAS01','A')
insert into PRODUTO_COSIF VALUES('2' , '2', 'CLAS02', 'A')
GO





